module LocalizeHelper
  DETAIL_WORD = "详细信息"
  PRODUCT_WORD = "产品"
  IMAGE_WORD = "图片"
  PRICE_WORD = "价格"
  UNIT_WORD = "单位"
  ORIGIN_WORD = "产地"
  UPDATE_WORD = "更新"
  INVENTORY_WORD = "库存"
  ORDER_WROD = "订单"
  USER_WORD = "人员"
  LOGIN_WORD = "登录"
  LOGOUT_WORD = "登出"
  PRODUCT_TYPE_WORD = "种类"
  TITLE_WORD = "名称"
  LIST_WORD = "列表"
  COUNTER_WORD = "专柜"
  NO_AUTORITIY_WORD = "无权限访问"
  REAL_NAME_WORD = "真实姓名"
  COMMENT_INFO_WORD = "备注信息"
  PHONE_NUMBER_WORD = "电话"
  RESTURANT_ADDRESS_WORD = "餐馆地址"
  IDENTIFY_NUMBER_WORD = "身份证号"
  USER_NAME_WORD = "用户名"
  PASSWORD_WORD = "密码"
  PASSWORD_CONFIRMATION_WORD = "再次确认密码"
  PRIORTIY_NAME_WORD = "权限"
end